pipeline {
    agent any
    environment {
		name="NAME"
    }
    stages {
        stage("Checkout Code") {
            steps {
                checkout scm
            }
        }
        stage("Build Docker Image") {
            steps {
                sh "docker build -t writetoshell:${BUILD_NUMBER} ."
            }
        }
    }
}